Use defmt:timestamp! macro instead of attribute form
This change fixes a compiler error in the CO2 sensor sessions:
```
error: expected attribute, found macro `defmt::timestamp`
  --> src/lib.rs:18:3
   |
18 | #[defmt::timestamp]
   |   ^^^^^^^^^^^^^^^^ not an attribute
```

The #[defmt::timestamp] attribute has been changed to a regular macro that works just like the logging macros
Cite: https://ferrous-systems.com/blog/knurling-changelog-13/